# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ebe89cb376587d55815e3024a3015e73b31db6adaddc260ff85d1339cb54ee5607e22376d654bde9936d8b4d3f5748cb4fc3c54540abd8b6b1e7d20bd5d09545

test:
  secret_key_base: 870e324bad06cd523ca6bc973ea0f37c726ad6aaff52b6aaddb61df3522064b9bd7b32e1b0639c1066339a57f9efaef85c1c23bf4b7e8615806e8146bd87229a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
